[2025-03-21T18:02:46.435+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T18:02:46.484+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T18:02:37.729545+00:00 [queued]>
[2025-03-21T18:02:46.507+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T18:02:37.729545+00:00 [queued]>
[2025-03-21T18:02:46.508+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T18:02:46.551+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): fetch_weather_tomorrow> on 2025-03-21 18:02:37.729545+00:00
[2025-03-21T18:02:46.588+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=537) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T18:02:46.619+0000] {standard_task_runner.py:72} INFO - Started process 544 to run task
[2025-03-21T18:02:46.627+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'fetch_weather_tomorrow', 'manual__2025-03-21T18:02:37.729545+00:00', '--job-id', '91', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmp6fmx9rs9']
[2025-03-21T18:02:46.653+0000] {standard_task_runner.py:105} INFO - Job 91: Subtask fetch_weather_tomorrow
[2025-03-21T18:02:48.051+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.fetch_weather_tomorrow manual__2025-03-21T18:02:37.729545+00:00 [running]> on host c25e9da6226b
[2025-03-21T18:02:48.250+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='fetch_weather_tomorrow' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T18:02:37.729545+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T18:02:37.729545+00:00'
[2025-03-21T18:02:48.254+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T18:02:48.959+0000] {python.py:240} INFO - Done. Returned value was:                                    id  ...                 created_at
0    b2bd0b3c4f0bd33f962b5e887ea4390d  ... 2025-03-21 18:02:48.759496
1    52390f6615815f3a4a42b453eb76363c  ... 2025-03-21 18:02:48.760937
2    be071f2658179672c42d0ee26ebd5c37  ... 2025-03-21 18:02:48.762108
3    c9e6fb6e4fd2091d238b86547401e76a  ... 2025-03-21 18:02:48.763440
4    cb8e8056f1091aa7e17e386d183efd1f  ... 2025-03-21 18:02:48.764569
..                                ...  ...                        ...
116  51229e011e66c3495a4c592cb2a4aa72  ... 2025-03-21 18:02:48.951277
117  24429a9906b22dde77071262f18c9965  ... 2025-03-21 18:02:48.952453
118  12fa5684f2a179a22ddc8a7aba189067  ... 2025-03-21 18:02:48.953645
119  5a86237697e6f0ae9fb2d1be0c98bbe2  ... 2025-03-21 18:02:48.954796
120  324ed0bddcd08ec445999db4a0e66825  ... 2025-03-21 18:02:48.955891

[121 rows x 6 columns]
[2025-03-21T18:02:49.028+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T18:02:49.030+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=fetch_weather_tomorrow, run_id=manual__2025-03-21T18:02:37.729545+00:00, execution_date=20250321T180237, start_date=20250321T180246, end_date=20250321T180249
[2025-03-21T18:02:49.144+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T18:02:49.587+0000] {taskinstance.py:3901} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-03-21T18:02:49.590+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
