[2025-03-22T04:18:51.425+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T04:18:51.471+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.check_and_insert_raw_data manual__2025-03-22T04:17:48.013302+00:00 [queued]>
[2025-03-22T04:18:51.492+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.check_and_insert_raw_data manual__2025-03-22T04:17:48.013302+00:00 [queued]>
[2025-03-22T04:18:51.493+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T04:18:51.522+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): check_and_insert_raw_data> on 2025-03-22 04:17:48.013302+00:00
[2025-03-22T04:18:51.533+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=452) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T04:18:51.536+0000] {standard_task_runner.py:72} INFO - Started process 454 to run task
[2025-03-22T04:18:51.536+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'check_and_insert_raw_data', 'manual__2025-03-22T04:17:48.013302+00:00', '--job-id', '234', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmp30otwued']
[2025-03-22T04:18:51.541+0000] {standard_task_runner.py:105} INFO - Job 234: Subtask check_and_insert_raw_data
[2025-03-22T04:18:51.915+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.check_and_insert_raw_data manual__2025-03-22T04:17:48.013302+00:00 [running]> on host c25e9da6226b
[2025-03-22T04:18:52.092+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='check_and_insert_raw_data' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T04:17:48.013302+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-22T04:17:48.013302+00:00'
[2025-03-22T04:18:52.096+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T04:18:52.161+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-22T04:18:58.685+0000] {weather-data-pipeline.py:192} INFO - üîç OpenMeteo Columns: Index(['id', 'datetime', 'temperature', 'area', 'source', 'created_at'], dtype='object')
[2025-03-22T04:18:58.689+0000] {weather-data-pipeline.py:193} INFO - üîç WeatherAPI Columns: Index(['id', 'datetime', 'temperature', 'area', 'source', 'created_at'], dtype='object')
[2025-03-22T04:18:58.691+0000] {weather-data-pipeline.py:194} INFO - üîç Tomorrow.io Columns: Index(['id', 'datetime', 'temperature', 'area', 'source', 'created_at'], dtype='object')
[2025-03-22T04:18:58.692+0000] {weather-data-pipeline.py:196} INFO - 
üîç Data Types:
id                     object
datetime       datetime64[ns]
temperature           float64
area                   object
source                 object
created_at     datetime64[ns]
dtype: object
[2025-03-22T04:18:58.696+0000] {weather-data-pipeline.py:197} INFO - 
üîç Data Types:
id                     object
datetime       datetime64[ns]
temperature           float64
area                   object
source                 object
created_at     datetime64[ns]
dtype: object
[2025-03-22T04:18:58.699+0000] {weather-data-pipeline.py:198} INFO - 
üîç Data Types:
id                     object
datetime       datetime64[ns]
temperature           float64
area                   object
source                 object
created_at     datetime64[ns]
dtype: object
[2025-03-22T04:18:58.701+0000] {weather-data-pipeline.py:200} INFO - 
üìä Shape (Jumlah Data): OpenMeteo: (336, 6), WeatherAPI: (168, 6), Tomorrow.io: (121, 6)
[2025-03-22T04:18:58.715+0000] {weather-data-pipeline.py:208} INFO - 
üöÄ Hasil Akhir (Gabungan DataFrame):
                                 id            datetime  temperature     area      source                 created_at
0  2f667e582722e7bfcc8c49373e7b1230 2025-03-15 00:00:00         26.8  Jakarta  Open Meteo 2025-03-22 04:18:53.944882
1  53f1db584152f7792d81b9fbd7f52ca0 2025-03-15 01:00:00         26.4  Jakarta  Open Meteo 2025-03-22 04:18:53.944882
2  551c49b66175ce3a497fc2e18ce604fa 2025-03-15 02:00:00         26.0  Jakarta  Open Meteo 2025-03-22 04:18:53.944882
3  741d65a2b99c99d5fe68591377691a64 2025-03-15 03:00:00         25.8  Jakarta  Open Meteo 2025-03-22 04:18:53.944882
4  a91776b020cc7659dc75e43c9bf3dd76 2025-03-15 04:00:00         25.8  Jakarta  Open Meteo 2025-03-22 04:18:53.944882
[2025-03-22T04:19:21.994+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T04:19:22.014+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T04:19:22.015+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=check_and_insert_raw_data, run_id=manual__2025-03-22T04:17:48.013302+00:00, execution_date=20250322T041748, start_date=20250322T041851, end_date=20250322T041922
[2025-03-22T04:19:22.098+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T04:19:22.149+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-22T04:19:22.152+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
