[2025-03-21T17:53:50.141+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-21T17:53:50.171+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T17:53:46.219569+00:00 [queued]>
[2025-03-21T17:53:50.187+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T17:53:46.219569+00:00 [queued]>
[2025-03-21T17:53:50.188+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-21T17:53:50.211+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_table_if_not_exists> on 2025-03-21 17:53:46.219569+00:00
[2025-03-21T17:53:50.225+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=361) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-21T17:53:50.230+0000] {standard_task_runner.py:72} INFO - Started process 370 to run task
[2025-03-21T17:53:50.231+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-two-source', 'create_table_if_not_exists', 'manual__2025-03-21T17:53:46.219569+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/weather-two-source.py', '--cfg-path', '/tmp/tmpym2hc5c4']
[2025-03-21T17:53:50.235+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask create_table_if_not_exists
[2025-03-21T17:53:50.335+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-two-source.create_table_if_not_exists manual__2025-03-21T17:53:46.219569+00:00 [running]> on host c25e9da6226b
[2025-03-21T17:53:50.861+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-two-source' AIRFLOW_CTX_TASK_ID='create_table_if_not_exists' AIRFLOW_CTX_EXECUTION_DATE='2025-03-21T17:53:46.219569+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-21T17:53:46.219569+00:00'
[2025-03-21T17:53:50.864+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-21T17:53:50.930+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-21T17:53:51.247+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-21T17:53:51.275+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-21T17:53:51.277+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-two-source, task_id=create_table_if_not_exists, run_id=manual__2025-03-21T17:53:46.219569+00:00, execution_date=20250321T175346, start_date=20250321T175350, end_date=20250321T175351
[2025-03-21T17:53:51.378+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-21T17:53:51.755+0000] {taskinstance.py:3901} INFO - 2 downstream tasks scheduled from follow-on schedule check
[2025-03-21T17:53:51.759+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
