[2025-03-22T02:19:43.488+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-03-22T02:19:43.529+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_dim_tables scheduled__2025-03-22T01:00:00+00:00 [queued]>
[2025-03-22T02:19:43.548+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather-data-pipeline.create_insert_dim_tables scheduled__2025-03-22T01:00:00+00:00 [queued]>
[2025-03-22T02:19:43.549+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-03-22T02:19:43.574+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): create_insert_dim_tables> on 2025-03-22 01:00:00+00:00
[2025-03-22T02:19:43.588+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5675) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-03-22T02:19:43.588+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'weather-data-pipeline', 'create_insert_dim_tables', 'scheduled__2025-03-22T01:00:00+00:00', '--job-id', '209', '--raw', '--subdir', 'DAGS_FOLDER/weather-data-pipeline.py', '--cfg-path', '/tmp/tmpedh1pv7q']
[2025-03-22T02:19:43.593+0000] {standard_task_runner.py:72} INFO - Started process 5680 to run task
[2025-03-22T02:19:43.594+0000] {standard_task_runner.py:105} INFO - Job 209: Subtask create_insert_dim_tables
[2025-03-22T02:19:43.946+0000] {task_command.py:467} INFO - Running <TaskInstance: weather-data-pipeline.create_insert_dim_tables scheduled__2025-03-22T01:00:00+00:00 [running]> on host c25e9da6226b
[2025-03-22T02:19:44.169+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather-data-pipeline' AIRFLOW_CTX_TASK_ID='create_insert_dim_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-22T01:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-03-22T01:00:00+00:00'
[2025-03-22T02:19:44.172+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-03-22T02:19:44.209+0000] {base.py:84} INFO - Retrieving connection 'rizqi-neon'
[2025-03-22T02:19:44.530+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-03-22T02:19:44.550+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-03-22T02:19:44.551+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=weather-data-pipeline, task_id=create_insert_dim_tables, run_id=scheduled__2025-03-22T01:00:00+00:00, execution_date=20250322T010000, start_date=20250322T021943, end_date=20250322T021944
[2025-03-22T02:19:44.604+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-03-22T02:19:44.618+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
